version: "3"
services:

  frontend:
    build: 
      context: ./Telivery_FE 
    ports:
     - "3000:3000"
    container_name: frontend-con
    # volumes: 
    #   - 'our-vol:/app'
    restart: always
    image: run
    stdin_open: true

  backend:
    container_name: backend-con
    build: 
      context: ./Telivery_BE
#    restart: on-failure
    # depends_on:
    #   - mysqldb
    ports:
      - '8000:8000'
    # environment:
    #   spring.datasource.url: ""
    volumes:
      - ./Telivery_BE:/Telivery_BE
    # networks:
    #   - network-tier
    tty: true

  